version: "3.9"

 services:
  mysqldb:
   container_name: mysqldb
   image: mysql:8
   restart: unless-stopped
   environment:
     MYSQL_ROOT_PASSWORD: root
   volumes:
    - /home/mysql/data:/var/lib/mysql

  spring_app:
   image: seifeddin/achatproject
   container_name:achatbackend
   restart: on-failure
   ports:
    - 9090:8080
   depends_on:
     - mysqldb