version: '3.4'
services:
  super-app-db:
    image: mysql:8.0.28
    environment:
      - MYSQL_DATABASE: 'achat'
      - MYSQL_ROOT_PASSWORD: 'seifE$12'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/mysql/data:/var/lib/mysql

  spring_app:
   image: seifeddin/achatproject
   container_name: achatbackend
   restart: on-failure
   ports:
    - 9090:8080
   depends_on:
     - mysqldb
