version: '2'
volumes:
 dbdata:

services:
 mysql:
  image: mysql:8
  container_name: mysql
  volumes:
    - dbdata:/var/lib/mysql
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=achatdb
    - MYSQL_USER=root
    - MYSQL_PASSWORD=seifE$12
  ports:
    - "33061:3306"
