version: "3.5"
services:
    mysql:
        image: mysql:8
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: seifE$12
            MYSQL_USER: seif
            MYSQL_PASSWORD: seifE$12
            MYSQL_DATABASE: achatdb
        volumes:
            - /home/mysql/data:/var/lib/mysql
            - db_data:/var/lib/mysql
